phraseapp:
  sources:
    - file: "./config/locales/*.<locale_code>.yml"
      params:
        file_format: yml
    - file: "./webpack/**/*.<locale_code>.json"
      params:
        file_format: nested_json
  targets:
    - file: "./config/locales/<locale_code>.json"
      params:
        file_format: yml
